#ifndef _RETURN_INDICES_H
#define _RETURN_INDICES_H

#include "stm32l4xx.h"

void chronoamperometry_page0(void);
void chronoamperometry_page1(void);
void chrono_ocp_page0(void);
void linear_pulse_voltammetry_page0(void);
void cyclic_voltammetry_page0(void);
void differential_pulse_voltammetry_page0(void);
void normal_pulse_voltammetry_page0(void);
void squarewave_voltammetry_page0(void);


extern uint8_t EXP_NUM_ROW;
extern uint8_t EXP_NUM_COL;
extern uint8_t NUM_STEPS_ROW;
extern uint8_t NUM_STEPS_COL;
extern uint8_t VOLTAGE1;
extern uint8_t VOLTAGE_DURATION1;
extern uint8_t VOLTAGE2;
extern uint8_t VOLTAGE_DURATION2;
extern uint8_t VOLTAGE3;
extern uint8_t VOLTAGE_DURATION3;
extern uint8_t VOLTAGE4;
extern uint8_t VOLTAGE_DURATION4;
extern uint8_t OCP1_ROW;
extern uint8_t OCP1_COL;
extern uint8_t OCP1_COLLECT_ROW;
extern uint8_t OCP1_COLLECT_COL;
extern uint8_t OCP2_ROW;
extern uint8_t OCP2_COL;
extern uint8_t OCP2_COLLECT_ROW;
extern uint8_t OCP2_COLLECT_COL;
extern uint8_t OCP3_ROW;
extern uint8_t OCP3_COL;
extern uint8_t OCP3_COLLECT_ROW;
extern uint8_t OCP3_COLLECT_COL;
extern uint8_t OCP4_ROW;
extern uint8_t OCP4_COL;
extern uint8_t OCP4_COLLECT_ROW;
extern uint8_t OCP4_COLLECT_COL;
extern uint8_t SAMPLING_RATE_ROW;
extern uint8_t SAMPLING_RATE_COL;
extern uint8_t NUM_CYCLES_ROW;
extern uint8_t NUM_CYCLES_COL;
extern uint8_t ETX_ROW;
extern uint8_t ETX_COL;
extern uint8_t CRC_ROW;
extern uint8_t CRC_COL;
extern uint8_t CR_ROW;
extern uint8_t CR_COL;
extern uint8_t ETX1_ROW;
extern uint8_t ETX1_COL;
extern uint8_t PAGE_NUM_ROW;
extern uint8_t PAGE_NUM_COL;
extern uint8_t CR1_ROW;
extern uint8_t CR1_COL;
extern uint8_t OCP_MEAS_MODE_ROW;
extern uint8_t OCP_MEAS_MODE_COL;
extern uint8_t OCP_MEAS_PRD_ROW;
extern uint8_t OCP_MEAS_PRD_COL;
extern uint8_t OCP_MEAS_SLOPE;
extern uint8_t WE_NUM_ROW;
extern uint8_t WE_NUM_COL;
extern uint8_t INITIAL_VOLTAGE;
extern uint8_t VS_OCP_ROW;
extern uint8_t VS_OCP_COL;
extern uint8_t INITIAL_VOLT_DURATION;
extern uint8_t CURRENT_RANGE_ROW;
extern uint8_t CURRENT_RANGE_COL;
extern uint8_t AUTO_RANGE_ROW;
extern uint8_t AUTO_RANGE_COL;
extern uint8_t POST_CELL_EXP_STATE_ROW;
extern uint8_t POST_CELL_EXP_STATE_COL;
extern uint8_t HOURS_ROW;
extern uint8_t HOURS_COL;
extern uint8_t MINUTES_ROW;
extern uint8_t MINUTES_COL;
extern uint8_t SECONDS_ROW;
extern uint8_t SECONDS_COL;
extern uint8_t SWEEP_POTENTIAL1;
extern uint8_t SWEEP_POTENTIAL2;
extern uint8_t SWEEP_POTENTIAL3;
extern uint8_t SWEEP_POTENTIAL4;
extern uint8_t VSOCP_SWEEP1;
extern uint8_t VSOCP_SWEEP2;
extern uint8_t VSOCP_SWEEP1_ROW;
extern uint8_t VSOCP_SWEEP1_COL;
extern uint8_t VSOCP_SWEEP2_ROW;
extern uint8_t VSOCP_SWEEP2_COL;
extern uint8_t VSOCP_SWEEP3_ROW;
extern uint8_t VSOCP_SWEEP3_COL;
extern uint8_t VSOCP_SWEEP4_ROW;
extern uint8_t VSOCP_SWEEP4_COL;
extern uint8_t SWEEP_RATE;
extern uint8_t VOLTS_PER_POINT;
extern uint8_t PULSE_HEIGHT;
extern uint8_t PULSE_WIDTH;
extern uint8_t SWEEP_INCREMENT;
extern uint8_t FREQUENCY;
extern uint8_t STEP_TIME;
#endif
